function ddyn = dyn_pendulum_syms(tdummy,in2,udummy)
%DYN_PENDULUM_SYMS
%    DDYN = DYN_PENDULUM_SYMS(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Apr-2021 11:23:48

k = in2(5,:);
theta = in2(1,:);
theta_dot = in2(2,:);
ddyn = [theta_dot;k.*1.0e+1-theta_dot.*(5.3e+1./5.0)-sin(theta).*(9.81e+2./1.0e+2);0.0;0.0;0.0;1.0];
